### PR TITLE
Merge pull request #1 from bshifaw/bs_carrot_action

### PR DESCRIPTION
**Pull request by bshifaw**
added carrot action

### CODE REVIEW

**Comment by bshifaw** [comment]
#carrot({test_name}, {test_input_key}, {eval_input_key})

**Comment by bshifaw** [comment]
#carrot({test_name}, {test_input_key}, {eval_input_key})

**Comment by bshifaw** [comment]
#carrot({test_name}, {test_input_key}, {eval_input_key})

**Comment by bshifaw** [comment]
#carrot(Hello world md5sum test Version1.0, /home/bshifaw/test_carrot/wdl/helloWorld.json, /home/bshifaw/test_carrot/carrot/eval_helloWorld.input.json)

**Comment by bshifaw** [comment]
#carrot(Hello world md5sum test Version1.0 , /home/bshifaw/test_carrot/wdl/helloWorld.json, /home/bshifaw/test_carrot/carrot/eval_helloWorld.input.json)

**Comment by carrotwdltest** [comment]
### 💥CARROT💥 run failed to start for test Hello world md5sum test Version1.0
Reason: Error Run Error ResourceRequest: ProcessRequestError IO No such file or directory (os error 2)

**Comment by bshifaw** [comment]
#carrot(Hello world md5sum test Version1.0, HelloWorld.docker, eval_workflow.image_to_use)

**Comment by carrotwdltest** [comment]
### 💥CARROT💥 run failed to start for test Hello world md5sum test Version1.0
Reason: Error Run Error ResourceRequest: ProcessRequestError IO No such file or directory (os error 2)

**Comment by bshifaw** [comment]
#carrot(Hello world md5sum test Version1.0, HelloWorld.docker, eval_workflow.image_to_use)

**Comment by carrotwdltest** [comment]
### 💥CARROT💥 run failed to start for test Hello world md5sum test Version1.0
Reason: Error Run Error ResourceRequest: ProcessRequestError IO No such file or directory (os error 2)

**Comment by bshifaw** [comment]
#carrot(Hello world md5sum test Version1.0, HelloWorld.docker, eval_workflow.image_to_use)

**Comment by carrotwdltest** [comment]
### 💥CARROT💥 run failed to start for test Hello world md5sum test Version1.0
Reason: Error Run Error ResourceRequest: ProcessRequestError IO No such file or directory (os error 2)

**Comment by bshifaw** [comment]
#carrot(Hello world md5sum test Version1.0, HelloWorld.docker, eval_workflow.image_to_use)

**Comment by carrotwdltest** [comment]
### 💥CARROT💥 run failed to start for test Hello world md5sum test Version1.0
Reason: Error Run Error ResourceRequest: ProcessRequestError IO No such file or directory (os error 2)

**Comment by bshifaw** [comment]
#carrot(Hello world md5sum test Version1.0 , /home/bshifaw/test_carrot/wdl/helloWorld.json, /home/bshifaw/test_carrot/carrot/eval_helloWorld.input.json)

**Comment by carrotwdltest** [comment]
### 💥CARROT💥 run failed to start for test Hello world md5sum test Version1.0
Reason: Error Run Error ResourceRequest: ProcessRequestError IO No such file or directory (os error 2)

**Comment by bshifaw** [comment]
#carrot(Hello world md5sum test Version1.0, HelloWorld.docker, eval_workflow.image_to_use)

**Pull request closed without merging**
